### ISSUE TITLE
Problem with matplotlib version 3.3.3

### ISSUE THREAD

**Issue by ubach-ef** [jive-vlbi/sched#11]
Installing pysched 1.15.0 in a fresh anaconda enviroment using the yaml file installed a working pysched enviroment, but plots aren't working. There is a conflict with the most recent matplotlib version 3.3.3

`  File "/Users/uwebach/opt/miniconda3/envs/pySCHED/lib/python3.9/site-packages/pysched/plot.py", line 82, in convert
    return _to_ordinalf(value)
  File "/Users/uwebach/opt/miniconda3/envs/pySCHED/lib/python3.9/site-packages/pysched/plot.py", line 73, in _to_ordinalf
    return matplotlib.dates._to_ordinalf(d)
AttributeError: module 'matplotlib.dates' has no attribute '_to_ordinalf'
`

going back to matplotlib 3.2.2 helps and plots are working again.

**Comment by bobeldering** [comment]
Fixed in the new release (1.16.0).

Thanks for the bug report!
