### ISSUE TITLE
Graphical arrangement of menus

### ISSUE THREAD

**Issue by bmarcote** [jive-vlbi/sched#2]
This is a suggestion:
In the tab like "XY" (see Figure; same applies to "Uptime") the fields "Stations" and "Sources" could be re-arranged in the windows so "Sources" is vertically expanded until the bottom of the window; and "Stations" be shorter in width.

This would remove the unused white space in the "Linewidth" parameters and would allow to see more sources at the same time, as this is a parameter that typically contains a large number of values.

![Screen Shot 2020-05-07 at 09 50 20](https://user-images.githubusercontent.com/5698957/81272475-d3e36c80-904d-11ea-9682-c3bb7fca8faf.png)

**Comment by bobeldering** [comment]
Fixed in 1.6.0.
