### ISSUE TITLE
Keeping LBA setups up to date

### ISSUE THREAD

**Issue by bmarcote** [jive-vlbi/sched#28]
In general, the setups included in the standard distribution for the Australian Long Baseline Array (LBA) are out-of-date. The observatory keeps updating those setups in their ftp sever at:

```
ftp://ftp.atnf.csiro.au/pub/people/vlbi/sched_files 
```
The ftp directory contains the setup files in a similar format and name (e.g. `lbaXXcm-Xp-XIF.set`), plus the `stations*.dat` and `locations.dat` updates.

Would it be feasible to keep a periodic check on this directory and update the setups in pySCHED with these files?
I imagine that downloading the setups could be trivial, merging the stations/locations may require some extra effort.

With this information, pySCHED will work out-of-the-box for current LBA schedules too.

**Comment by bobeldering** [comment]
The LBA setup files from the FPT server have been added/updated in the pySCHED repository.
The daily pySCHED test checks for updates (but only notifies updates, it still requires a manual commit to the repository).
