### ISSUE TITLE
[Maybe unfeasible] Save previous state during minor key-file updates

### ISSUE THREAD

**Issue by bmarcote** [jive-vlbi/sched#3]
This is a suggestion for a future behavior improvement, but at the same time I realize that I am actually not sure about to which extent it is feasible.

From a user point of view, this is the typical use of (py)SCHED most of the times:
- Prepare a first draft of the schedule.
- The frequency/station part is typically set properly here so should not change a posteriori.
- Compile the schedule for the first time.
- Start an iterative process where changes in the scans (durations, gaps, etc) are made in order to fit the allocated time. This will typically require several compilations of the schedule.

Given that it seems like (I think) a significant fraction of the computing time is spent in the station/frequency setup, and the compiling time are significant larger than in SCHED, could it be possible to follow some approach like the following one? (in a similar way to the stored .catalog files; to significantly short the times for the secondary compilations):
- If no temp files, run as usual.
- Store all the parts from the initial schedule into a temp file (probably .XXX in the current directory)? Note that I am not sure how the data flow goes, so not sure if there is a station/freq processing that can be store before computing the different scans.
- If only modifications in the scan section from the .key file are made (I would require storing the previous one), jump directly to the processing of this part.

This would help the longer waiting times that are currently required when (most of the cases), only a couple of scans have been modified.

Again, not sure if this is possible at all. But just a few random thoughts I was curious about :-)

**Comment by bobeldering** [comment]
I finally had some time to look into the runtime of pySCHED. While I don't see a way to store intermediate results in a way that is both useful in reducing the runtime and has easy to understand limitations, I did spend some time profiling pySCHED. A few identified runtime bottlenecks are improved in version 1.12.

To put some number to it: running the whole test suite now runs in 13 minutes from 21 minutes and one of the most basic examples (eg1024) is reduced from 8.5 seconds to 5 seconds.

If you have a schedule that seems to take particularly long to schedule, please post it here or send it by email. It could help to get a sense of where to look for further improvements.
