### ISSUE TITLE
Releases and SCHED 11.6

### ISSUE THREAD

**Issue by varenius** [jive-vlbi/sched#4]
I just read the email about pySCHED being released - this is Great news! Well done everyone.

I wonder: how is the continued evolution of SCHED tied to pySCHED? 
In particular I note that https://github.com/jive-vlbi/sched/blob/python/README.md contains a part of the early release-history, up to 1.2.0, but the "Releases"-tab shows more releases after this date. Does any of them include SCHED 11.6 which was announced via email May 19 2020 by Jim Jacobs as

> The latest release of sched (version 11.6) is available from ftp.aoc.nrao.edu via anonymous ftp.  Once logged in the release file is
> 
>     /pub/software/sched/sched_11.6/sched_11.6.tgz
> 
> The compressed tar archive contains sources, binaries for  Linux (several variants), documentation and catalogs.  The code contains virtually no changes: the release was motivated by updated antenna positions provided by Goddard Space Flight Center.  Nota Bene: Ongoing, long-term observations might want to continue using the older antenna positions to avoid a change in mid experiment.

Are the antenna positions in pySCHED even more recent than SCHED 11.6?

**Comment by bobeldering** [comment]
The merge with 11.6 hasn't happened yet. We didn't want to use it for the May/June EVN session. But in general, the plan is to incorporate any changes to SCHED into pySCHED. The catalog changes from SCHED 11.6 should be merged soon.

**Comment by bobeldering** [comment]
pySCHED has now been merged with the code and catalogs of SCHED 11.6.
